[ampq]
connStr = "amqp://guest:guest@localhost:5672/"
queue = "hotelsOut"
errorQueue = "error"

[sx]
endpoint= "http://localhost:8080/sxcs/outgoingRequests"
connString= "user/password@localhost:1521/AIXPFMS"
